Add wf
nicolecastillo/xlearn pull request #6
Opened 2020-07-02 19:14 UTC by nicolecastillo

- Adds folder with the scripts and the workflow file.

2020-07-04 00:03 UTC, ivotron requested changes
looking really good! almost done

2020-07-04 00:03 UTC, ivotron commented on demo/classification/higgs/popper/README.md
> +2. Install docker.
we can add a link to the installation instructions

2020-07-04 00:03 UTC, ivotron commented on demo/classification/higgs/popper/README.md
> +[Popper](https://github.com/systemslab/popper) is a tool for defining and executing container-native workflows in Docker, as well as other container engines. This workflow contains a `wf.yml` file th
we can expand this to describe what the workflow is doing (comparing xlearn with liblinear). We can also expand a bit on how each are executed (pandas), the number of times each task gets executed, the fact that the charts show error bars, etc.

2020-07-04 00:03 UTC, ivotron commented on demo/classification/higgs/popper/README.md
> +
another thing we could add is a precomputed graph, like the ones they have in the readme. We can add the image file as an attachment to this PR, which will generate a link, and we can use this link in the README, so that we avoid having to put the image inside the git repository

2020-07-04 00:03 UTC, ivotron commented on demo/classification/higgs/popper/Dockerfile
> +RUN git clone https://github.com/cjlin1/liblinear /opt/liblinear && \
this can checkout a specific commit so that it always runs the same version

2020-07-04 00:03 UTC, ivotron commented on demo/classification/higgs/popper/Dockerfile
> +    make -j16
we might want to lower this to 4

2020-07-04 00:10 UTC, ivotron commented on demo/classification/higgs/popper/README.md
> +```
one other thing I forgot to mention: we can show an example of how to run a single step, and also how to run a step in interactive mode (`popper sh`)

2020-07-04 00:15 UTC, ivotron commented on demo/classification/higgs/popper/README.md
> +[Popper](https://github.com/systemslab/popper) is a tool for defining and executing container-native workflows in Docker, as well as other container engines. This workflow contains a `wf.yml` file th
You can take the point of view of a reader such as yourself, when you were starting to look at this project a month ago (wow, you moved really fast!), and how you'd liked to have a README like this to explain from a high-level point of view what this test does, and what each library do, etc..

2020-07-05 20:07 UTC, nicolecastillo commented
![report](https://user-images.githubusercontent.com/33427324/86541248-39be6a00-bec0-11ea-8961-132951ac028f.png)

2020-07-06 16:38 UTC, ivotron requested changes
really nice! The only thing I forgot to mention is that we can add 1-2 sentences to the README in the `demo/higgs/` folder to mention that a comparison of xlearn with liblinear is included in the `popper/` workflow.

2020-07-06 17:45 UTC, nicolecastillo commented
Right! I'll get on it.

2020-07-06 19:12 UTC, merged